<img src="https://raw.githubusercontent.com/carubbi/MQ/b58af070c45fb17b77640c06c0016859ad366b4d/notebooks/assets/imgs/UNIFOR_logo.png" width="400">
<br>
<b>
<font size="6" face="arial" color="blue">
    Graduação em Ciência da Computação
</font>
</b>
<br>
<b>
<font size="4" face="arial">
    Disciplina: Métodos Quantitativos em Computação
</font>
</b>

**Orientador: Prof. Me. Ricardo Carubbi** <br>
*Docente da Graduação e Pós-Graduação em Ciência de Dados e Inteligência Artificial*<br>
*Laboratório de Ciência de Dados e Inteligência Artificial*<br>
*Universidade de Fortaleza*<br>
**Discentes:**<br>
Arthur Ramos Souza - 2513831<br>
Samylla Miguel Barbosa - 2517429

#AP 1 — AMES HOUSING
Como se distribuem e variam os preços de venda de imóveis residenciais?

###Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Testando raw/AmesHousing.csv

In [ ]:
url = "https://www.kaggle.com/api/v1/datasets/download/shashanknecrothapa/ames-housing-dataset/AmesHousing.csv"
dataframe = pd.read_csv(url)
dataframe.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

### 1. Importação e rastreabilidade

**Identificação e Procedência:** O arquivo `AmesHousing.csv` foi importado diretamente de uma URL do Kaggle, conforme especificado no código. A importação foi realizada com a biblioteca `pandas`, utilizando `pd.read_csv()`, que infere automaticamente o separador (vírgula) e a codificação (UTF-8, por padrão para arquivos CSV comuns) quando não especificados e o faz com sucesso.

**Importação do arquivo bruto:** O arquivo foi importado diretamente da fonte, sem alterações na cópia original. Embora não tenhamos um diretório `data/raw/` local para armazenamento explícito do arquivo bruto, a leitura direta da URL garante que a versão original seja utilizada. Para fins de preservação lógica, criaremos uma cópia do DataFrame após a importação.

**Verificação de separador, codificação, dimensões e unidade de análise:**
*   **Separador e Codificação:** A leitura bem-sucedida do arquivo `AmesHousing.csv` pelo `pandas` confirma que o separador `,` (vírgula) e a codificação `UTF-8` foram corretamente identificados e utilizados.
*   **Dimensões:** O dataset possui 2930 linhas e 82 colunas, conforme a saída `(2930, 82)` do comando `dataset.shape` e a informação de `RangeIndex` e `Data columns` do `dataset.info()`.
*   **Unidade de Análise:** Cada linha do dataset representa uma observação única de um **imóvel residencial** vendido na cidade de Ames, Iowa, com suas características associadas. Portanto, a unidade de análise é o **imóvel**.

In [ ]:
print(dataframe.shape)
print(dataframe.columns.tolist())

(2930, 82)
['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition', 'SalePrice']

###Colunas Selecionadas:


*   SalePrice
*   Gr Liv Area
*   Yr Sold
*   Fence
* Fireplaces
* Mas Vnr Area (*)
* Year Remod/Add
* Year Built

In [ ]:
cols_sel = ["SalePrice", "Gr Liv Area", "Yr Sold", "Fence", "Fireplaces", "Mas Vnr Area", "Year Remod/Add", "Year Built"]
df_sel = dataframe[cols_sel].copy()
df_sel.head()

,SalePrice,Gr Liv Area,Yr Sold,Fence,Fireplaces,Mas Vnr Area,Year Remod/Add,Year Built
0,215000,1656,2010,NaN,2,112.0,1960,1960
1,105000,896,2010,MnPrv,0,0.0,1961,1961
2,172000,1329,2010,NaN,0,108.0,1958,1958
3,244000,2110,2010,NaN,2,0.0,1968,1968
4,189900,1629,2010,MnPrv,1,0.0,1998,1997

###Análise de colunas:

In [ ]:
df_sel.dtypes

SalePrice           int64
Gr Liv Area         int64
Yr Sold             int64
Fence              object
Fireplaces          int64
Mas Vnr Area      float64
Year Remod/Add      int64
Year Built          int64
dtype: object